credentials:
  usernames:
    # Esta seção começará vazia. Os usuários se registrarão pelo próprio app.
    # Se quiser, pode adicionar um admin aqui manualmente depois de gerar o hash da senha.
    # Exemplo:
    # admin:
    #   email: admin@example.com
    #   name: Admin User
    #   password: 'SEU_HASH_DA_SENHA_AQUI'
cookie:
  expiry_days: 30
  key: asparaginatriptofano2901 # Mude para uma string aleatória!
  name: siftcookie1998 # Mude para um nome aleatório!
preauthorized:
  emails: []